I'm using the June 2025 Digital City Map from [here](https://www.nyc.gov/content/planning/pages/resources/datasets/digital-city-map)

In [7]:
import geopandas as gpd
import matplotlib.pyplot as plt

# Read the shapefile
df = gpd.read_file('data/DCM_StreetCenterLine.shp')
df.head()

,Borough,Feat_Type,Feat_statu,Street_NM,HonoraryNM,Old_ST_NM,Streetwidt,Route_Type,RoadwayTyp,Build_Stat,Record_ST,Paper_ST,Stair_ST,CCO_ST,Marg_Wharf,Edit_Date,Shape_Leng,geometry
0,Staten Island,Mapped_St,City_St,Ellis Street,None,None,90,Gen_use,Surface_ST,Improved,N,N,N,N,N,NaT,119.470635,"LINESTRING Z (914472.428 126532.336 0, 914371...."
1,Staten Island,Mapped_St,City_St,Bamberger Lane,None,None,50,Gen_use,Surface_ST,Improved,N,N,N,N,N,NaT,525.598640,"LINESTRING Z (937763.891 136995.709 0, 937846...."
2,Bronx,Mapped_St,City_St,Nereid Avenue,None,None,100,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,1865.001879,"MULTILINESTRING Z ((1023332.375 267253.299 0, ..."
3,Bronx,Mapped_St,City_St,Split Rock Road,None,None,50,Gen_use,Walkway,Improved,N,N,N,N,N,NaT,138.833987,"LINESTRING Z (1035784.873 263086.754 0, 103575..."
4,Bronx,Mapped_St,City_St,East 178 Street,None,None,30,Gen_use,Surface_ST,Improved,N,N,N,N,N,NaT,426.849470,"LINESTRING Z (1017254.68 245892.932 0, 1017625..."

In [19]:
df['Street_NM'] = df['Street_NM'].str.lower()
df['words_count'] = df['Street_NM'].str.count(" ")+1
df.sort_values('words_count', ascending=False).head(10)

,Borough,Feat_Type,Feat_statu,Street_NM,HonoraryNM,Old_ST_NM,Streetwidt,Route_Type,RoadwayTyp,Build_Stat,Record_ST,Paper_ST,Stair_ST,CCO_ST,Marg_Wharf,Edit_Date,Shape_Leng,geometry,words_count
15879,Manhattan,Mapped_St,City_St,at the harlem river driveway / polo grounds se...,Willie Mays Drive,None,98,Artrl,Surface_ST,Improved,N,N,N,N,N,NaT,2168.215576,"LINESTRING Z (1000822.735 241805.682 0, 100083...",10
12727,Bronx,Mapped_St,City_St,east 207 street - msgr. john c. mccarthy place,None,None,70,Gen_use,Surface_ST,Improved,N,N,N,N,N,NaT,852.954750,"LINESTRING Z (1017557.744 258352.789 0, 101840...",9
9154,Manhattan,Mapped_St,City_St,east 43 street - archbishop fulton j. sheen place,None,None,60,Gen_use,Surface_ST,Improved,N,N,N,N,N,NaT,506.702441,"LINESTRING Z (991021.998 213293.825 0, 991465....",9
45945,Brooklyn,Mapped_St,City_St,lewis avenue / dr. sandy f. ray boulevard,None,None,70,Gen_use,Surface_ST,Improved,N,N,N,N,N,NaT,268.718822,"LINESTRING Z (1001828.07 190968.967 0, 1001787...",8
45940,Brooklyn,Mapped_St,City_St,lewis avenue / dr. sandy f. ray boulevard,None,None,70,Gen_use,Surface_ST,Improved,N,N,N,N,N,NaT,269.550645,"LINESTRING Z (1001623.479 192301.988 0, 100158...",8
45941,Brooklyn,Mapped_St,City_St,lewis avenue / dr. sandy f. ray boulevard,None,None,70,Gen_use,Surface_ST,Improved,N,N,N,N,N,NaT,268.617625,"LINESTRING Z (1001664.229 192036.479 0, 100162...",8
45942,Brooklyn,Mapped_St,City_St,lewis avenue / dr. sandy f. ray boulevard,None,None,70,Gen_use,Surface_ST,Improved,N,N,N,N,N,NaT,271.737685,"LINESTRING Z (1001705.453 191767.887 0, 100166...",8
45943,Brooklyn,Mapped_St,City_St,lewis avenue / dr. sandy f. ray boulevard,None,None,70,Gen_use,Surface_ST,Improved,N,N,N,N,N,NaT,266.926092,"LINESTRING Z (1001745.946 191504.05 0, 1001705...",8
45944,Brooklyn,Mapped_St,City_St,lewis avenue / dr. sandy f. ray boulevard,None,None,70,Gen_use,Surface_ST,Improved,N,N,N,N,N,NaT,272.630246,"LINESTRING Z (1001787.305 191234.575 0, 100174...",8
45957,Brooklyn,Mapped_St,City_St,lewis avenue / dr. sandy f. ray boulevard,None,None,70,Gen_use,Surface_ST,Improved,N,N,N,N,N,NaT,268.046015,"LINESTRING Z (1002319.342 187768.065 0, 100227...",8

#### The below list of street types is based on my own knowledge of roads and was supplemented by some research (and just zooming around on Google Maps to make sure I'm not missing any obvious road types)

In [29]:
street_types = ['avenue', 'boulevard', 'bridge', 'court', 'concourse', 'drive', 'expressway', 'highway', 'lane', 'parkway', 'plaza', 'road', 'row', 'street', 'terrace', 'turnpike', 'way']

#### Then I defined a simple function that uses a list comprehension to return all the matching words in the street names then applied the function to my `Street_NM` column

In [33]:
def street_types_analysis (words):
    matches = [word for word in words if word in street_types]
    return " ".join(matches)

In [34]:
df['ind_street_type'] = df['Street_NM'].str.split().apply(street_types_analysis)
df.head()

,Borough,Feat_Type,Feat_statu,Street_NM,HonoraryNM,Old_ST_NM,Streetwidt,Route_Type,RoadwayTyp,Build_Stat,Record_ST,Paper_ST,Stair_ST,CCO_ST,Marg_Wharf,Edit_Date,Shape_Leng,geometry,words_count,ind_street_type
0,Staten Island,Mapped_St,City_St,ellis street,None,None,90,Gen_use,Surface_ST,Improved,N,N,N,N,N,NaT,119.470635,"LINESTRING Z (914472.428 126532.336 0, 914371....",2,street
1,Staten Island,Mapped_St,City_St,bamberger lane,None,None,50,Gen_use,Surface_ST,Improved,N,N,N,N,N,NaT,525.598640,"LINESTRING Z (937763.891 136995.709 0, 937846....",2,lane
2,Bronx,Mapped_St,City_St,nereid avenue,None,None,100,Mjr_st,Surface_ST,Improved,N,N,N,N,N,NaT,1865.001879,"MULTILINESTRING Z ((1023332.375 267253.299 0, ...",2,avenue
3,Bronx,Mapped_St,City_St,split rock road,None,None,50,Gen_use,Walkway,Improved,N,N,N,N,N,NaT,138.833987,"LINESTRING Z (1035784.873 263086.754 0, 103575...",3,road
4,Bronx,Mapped_St,City_St,east 178 street,None,None,30,Gen_use,Surface_ST,Improved,N,N,N,N,N,NaT,426.849470,"LINESTRING Z (1017254.68 245892.932 0, 1017625...",3,street

In [35]:
df['street_type_count'] = df['ind_street_type'].str.count(' ')+1

In [38]:
df.sort_values('street_type_count', ascending=False).head(10)

,Borough,Feat_Type,Feat_statu,Street_NM,HonoraryNM,Old_ST_NM,Streetwidt,Route_Type,RoadwayTyp,Build_Stat,...,Paper_ST,Stair_ST,CCO_ST,Marg_Wharf,Edit_Date,Shape_Leng,geometry,words_count,ind_street_type,street_type_count
8077,Brooklyn,Mapped_St,City_St,adams street - brooklyn bridge boulevard,None,None,160,Artrl,Surface_ST,Improved,...,N,N,N,N,NaT,2293.582712,"LINESTRING Z (987365.738 192920.349 0, 987369....",6,street bridge boulevard,3
11841,Staten Island,Mapped_St,City_St,south bridge street,None,None,60,Gen_use,Surface_ST,Improved,...,N,N,N,N,NaT,163.184719,"LINESTRING Z (919057.399 130485.231 0, 918948....",3,bridge street,2
45944,Brooklyn,Mapped_St,City_St,lewis avenue / dr. sandy f. ray boulevard,None,None,70,Gen_use,Surface_ST,Improved,...,N,N,N,N,NaT,272.630246,"LINESTRING Z (1001787.305 191234.575 0, 100174...",8,avenue boulevard,2
45952,Brooklyn,Mapped_St,City_St,lewis avenue / dr. sandy f. ray boulevard,None,None,70,Gen_use,Surface_ST,Improved,...,N,N,N,N,NaT,270.965627,"LINESTRING Z (1002114.883 189100.23 0, 1002073...",8,avenue boulevard,2
45951,Brooklyn,Mapped_St,City_St,lewis avenue / dr. sandy f. ray boulevard,None,None,70,Gen_use,Surface_ST,Improved,...,N,N,N,N,NaT,268.828375,"LINESTRING Z (1002073.776 189368.059 0, 100203...",8,avenue boulevard,2
45950,Brooklyn,Mapped_St,City_St,lewis avenue / dr. sandy f. ray boulevard,None,None,70,Gen_use,Surface_ST,Improved,...,N,N,N,N,NaT,269.767057,"LINESTRING Z (1002032.994 189633.776 0, 100199...",8,avenue boulevard,2
45949,Brooklyn,Mapped_St,City_St,lewis avenue / dr. sandy f. ray boulevard,None,None,70,Gen_use,Surface_ST,Improved,...,N,N,N,N,NaT,267.174382,"LINESTRING Z (1001992.07 189900.421 0, 1001951...",8,avenue boulevard,2
45948,Brooklyn,Mapped_St,City_St,lewis avenue / dr. sandy f. ray boulevard,None,None,70,Gen_use,Surface_ST,Improved,...,N,N,N,N,NaT,273.125803,"LINESTRING Z (1001951.539 190164.503 0, 100191...",8,avenue boulevard,2
45946,Brooklyn,Mapped_St,City_St,lewis avenue / dr. sandy f. ray boulevard,None,None,70,Gen_use,Surface_ST,Improved,...,N,N,N,N,NaT,269.670824,"LINESTRING Z (1001868.98 190702.417 0, 1001828...",8,avenue boulevard,2
45945,Brooklyn,Mapped_St,City_St,lewis avenue / dr. sandy f. ray boulevard,None,None,70,Gen_use,Surface_ST,Improved,...,N,N,N,N,NaT,268.718822,"LINESTRING Z (1001828.07 190968.967 0, 1001787...",8,avenue boulevard,2